#!/usr/bin/env bash
# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
set -Eeuo pipefail #-x
die() { echo "${BASH_SOURCE[0]##*/}: **ERROR**: ${*:-aborting}" >&2; exit 127 ; }
ABSPATHSCRIPT=$(readlink -f "${BASH_SOURCE[0]}")	# Resolve symlinks to find installdir

# == Setup & Options ==
source "${ABSPATHSCRIPT%/*}"/lib/setup.sh	# preflight.sh common.sh
jjfzf_tempd					# assigns $JJFZF_TEMPD
ENTER=
PRINTOUT=
WITH_PREVIEW=true
while test $# -ne 0 ; do
  case "$1" in \
    --version)		echo "${ABSPATHSCRIPT##*/} `$JJFZF_ABSPATHLIB/../version.sh`"; exit ;;
    --help-bindings)	PRINTOUT="$1" ;;
    -h|--help)		echo "Usage: ${ABSPATHSCRIPT##*/} [--man] [--version] [OPTIONS...]"; exit ;;
    -c|+c|-r|+r|-s)	ENTER="$1" ;;
    --man)		exec man $JJFZF_ABSPATHLIB/../doc/jj-fzf.1 ;;
    --no-preview)	WITH_PREVIEW=false ;;
    -x)			set -x ;;
    *)         		break ;;
  esac
  shift
done

# == Config ==
export JJFZF_REVSET_OVERRIDE="$JJFZF_TEMPD/log_revset"
# Always ensure root relative paths
JJROOT="$(jj --ignore-working-copy --no-pager root 2>/dev/null)" &&
  cd "$JJROOT" ||
    die "$PWD: not a JJ repository"
JJ="jj --no-pager --ignore-working-copy"
export JJFZFT="$JJ log --no-graph -T"
RELOAD="reload-sync(cat $JJFZF_TEMPD/jjfzf_list)"	# see jjfzf_load

# == jjfzf_full_commit ==
# Show commit(s) with diff and full info
jjfzf_full_commit()
(
  set -Eeuo pipefail
  test -z "${1-}" &&	# may be revset
    exit 0
  jjfzf_jjlog "$JJFZF_LOG_DETAILED_CONFIG" $JJFZF_COLOR --no-graph -r "$1" -p \
	      -T '"\n" ++ concat( builtin_log_oneline , builtin_log_detailed , diff.stat() , "\n" )'
)
export -f jjfzf_full_commit
jjfzf_log_detailed	# for preview, assigns $JJFZF_LOG_DETAILED_CONFIG

# == jjfzf_full_history ==
jjfzf_full_history()
(
  set -Eeuo pipefail
  REVSET="${1-@}"
  jjfzf_full_commit "$REVSET" |
    sed '1{/^$/d}' |
    $JJFZF_PAGER
)
export -f jjfzf_full_history

# == Key Bindings ==
BINDINGS=()
declare -A POST
declare -A KEY
declare -A RUN
declare -A DOC

# Abandon
KEY[abandon]="Alt-A"
RUN[abandon]="jjfzf_run jj --no-pager abandon {+2}"
DOC[abandon]='Use `jj abandon` to abandon the currently selected revisions.'

# Commit
KEY[commit]="Alt-C"	POST[commit]="+first"
RUN[commit]="JJFZF_EDITOR=\"${JJ_EDITOR-}\" JJ_EDITOR=\"$JJFZF_ABSPATHLIB/editor.sh\" jjfzf_run +e jj commit -i"
DOC[commit]='Use `jj commit` to describe the currently selected revision and create a new child revision as working-copy.'

# Delete bookmarks & tags
KEY[bookmark]="Alt-B"
DOC[bookmark]='Create, move, delete jj bookmarks and git tags.'
RUN[bookmark]="jjfzf_run +x +e '$JJFZF_ABSPATHLIB'/bookmarks.sh -m {2}"

# Diffedit interactively
KEY[diffedit]="Alt-E"
RUN[diffedit]="jjfzf_run +e jj --no-pager diffedit -r {2}"
DOC[diffedit]='Use `jj diffedit` to interactively select content diff hunks to be kept in the currently selected revision, the rest is discarded.'

# Split files --without-description
jjfzf_filesplit()
(
  set -Eeuo pipefail
  COMMIT="$1"
  # read files affected by $COMMIT
  mapfile -t MAPFILE < <(jj --no-pager diff --name-only -r "$COMMIT")
  [[ ${#MAPFILE[@]} -gt 1 ]] ||
    return
  # create n-1 new commits from n files
  while [[ ${#MAPFILE[@]} -gt 1 ]] ; do
    unset 'MAPFILE[-1]' # unset 'MAPFILE[${#MAPFILE[@]}-1]'
    export JJ_EDITOR='true' # Override ui.editor to implement --without-description
    jjfzf_run +n jj split -m= -r "$COMMIT" -- "${MAPFILE[@]}"
  done
  jjfzf_run
)
export -f jjfzf_filesplit
KEY[filesplit]="Alt-F"
RUN[filesplit]="jjfzf_filesplit {2}"
DOC[filesplit]='Use `jj split` in a loop to split each file modified by the currently selected revision into its own commit.'

# Showkeys
# KEY[showkeys]="Alt-H"	# TODO: add for --help
BINDINGS+=( --header-label "$(echo ' Alt-H: Toggle Key Display ⫶ Ctrl-H: help ' | jjfzf_bold_keys)" )
BINDINGS+=( --bind "alt-h:execute-silent( jjfzf_config toggle jj-fzf.show-keys )" )	# see also transform-header
DOC[showkeys]='Display or hide the list of avilable key bindings, persist the setting in `jj-fzf.show-keys` of the `jj` user config.'

# Help
# KEY[help]="Ctrl-H"	# TODO: add for --help
BINDINGS+=( --bind "ctrl-h:execute( '$ABSPATHSCRIPT' --man )" )
DOC[help]='Show jj-fzf manual page.'

# Split interactively
KEY[split]="Alt-I"
RUN[split]="jjfzf_split_i {2}"
DOC[split]='Use `jj split` to interactively select content diff hunks to be split into a new commit with an empty description.'
jjfzf_split_i()
(
  set -Eeuo pipefail
  # Split without message editing, instead keep only the first (original) description
  touch "$JJFZF_TEMPD/skip1"
  export POPFILE_LIST= KEEPFILE_LIST="$JJFZF_TEMPD/skip1"
  export JJ_EDITOR="$JJFZF_ABSPATHLIB/popfile.sh" # Override ui.editor and implement --without-description
  jjfzf_run +e jj split -m= --interactive -r "$1"
)
export -f jjfzf_split_i

# Inject commit
KEY[inject]="Alt-J"
RUN[inject]="jjfzf_inject --diff @ {2} ; jjfzf_load_and_status"
DOC[inject]='Inject the currently selected revision as historic diff before @ while preserving its content.'

# New-A
KEY[new-a]="Alt-N"
RUN[new-a]="jjfzf_run jj --no-pager new --no-edit --insert-after {2}"
DOC[new-a]='Use `jj new --no-edit --insert-after` to create and insert a new revision after the currently selected revision. Add `Ctrl` to use `--insert-before` instead.'
BINDINGS+=( --bind "ctrl-alt-n:execute( jjfzf_run jj --no-pager new --no-edit -B {2} )+$RELOAD+down" )

# Absorb a content diff into mutable ancestors
KEY[absorb]="Alt-O"
RUN[absorb]="jjfzf_run jj --no-pager absorb --from {2}"
DOC[absorb]='Use `jj absorb` to split the content diff of the current revision and squash pieces into related mutable ancestors.'

# Reparent Commits
KEY[reparent]="Alt-P"
DOC[reparent]='Change parent(s) of the current revision by adding a new or removing an existing parent, and optionally simplify the parent list.'
RUN[reparent]="jjfzf_run +x +e '$JJFZF_ABSPATHLIB'/reparent.sh {+2}"

# Squash
KEY[squash]="Alt-Q"
RUN[squash]="jjfzf_squash {2} {+2}"
DOC[squash]='Use `jj squash` to move the changes from all selected revisions into the revision under the cursor.'
jjfzf_squash()
(
  set -Eeuo pipefail
  TARGET="${1-}"; shift
  ALL="$(jjfzf_ccrevs "$@")"
  if test -n "$TARGET" ; then
    test "$TARGET" == "$ALL" && TARGET="$TARGET-"
    if test -n "$($JJFZFT 'true' -r "~$TARGET & ($ALL)")"; then
      if [[ true == $($JJFZFT 'true' -r "@ & ($ALL)") ]]; then
	# The working copy @ is to be squashed. Squashing without --keep-emptied would start a new branch at @- which
	# is undesired if @+ exists. But using --keep-emptied does not squash the message. As a workaround, create a
	# new @+, so we never squash directly from @. This new working copy will receive any children from the
	# original squashed working copy.
	jjfzf_run +n jj --no-pager new --insert-after @
      fi
      jjfzf_run jj --no-pager squash --from "$ALL" --into "$TARGET"
      return # already called jjfzf_load_and_status
    fi
  fi
  # else
  jjfzf_load_and_status
)
export -f jjfzf_squash

# Restore
KEY[restore]="Alt-S"
RUN[restore]="jjfzf_restore {2} {+2}"
DOC[restore]='Use `jj restore` to interactively select changes to be restored from a selected revisions into the revision under the cursor. Add `Ctrl` to run with `--restore-descendants`.'
BINDINGS+=( --bind "ctrl-alt-s:execute( jjfzf_restore --restore-descendants {2} {+2} )+$RELOAD" )
jjfzf_restore()
(
  set -Eeuo pipefail
  ARGS=()
  while [[ "${1-}" == --* ]] ; do
    ARGS+=("$1") && shift
  done
  TARGET="${1-}"; shift
  ALL="$(jjfzf_ccrevs "$@")"
  if test -n "$TARGET" ; then
    test "$TARGET" == "$ALL" && TARGET="$TARGET-"
    if test -n "$($JJFZFT 'true' -r "~$TARGET & ($ALL)")"; then
      jjfzf_run jj restore --interactive --from "$ALL" --into "$TARGET" "${ARGS[@]}"
      return # already called jjfzf_load_and_status
    fi
  fi
  # else
  jjfzf_load_and_status
)
export -f jjfzf_restore

# Rebase Commits
KEY[rebase]="Alt-R"
DOC[rebase]='Use `jj rebase` or `jj duplicate` to move or copy a set of revisions (possibly with descendants), onto, before or after another revision. Also supports `jj simplify-parents` afterwards.'
RUN[rebase]="jjfzf_run +x +e '$JJFZF_ABSPATHLIB'/rebase.sh {+2}"

# Revert Commits
KEY[revert]="Alt-V"	POST[revert]="+first"
RUN[revert]="jjfzf_run jj --no-pager revert -d @ -r \$(jjfzf_ccrevs {+2})"
DOC[revert]='Use `jj revert` to create new commits that undo the changes made by the currently selected revisions and apply the changes on top of the working-copy.'

# Swap
KEY[swap]="Alt-X"	POST[swap]="+down"
RUN[swap]="jjfzf_run jj --no-pager rebase --insert-before {2}- -r {2}"
DOC[swap]='Use `jj rebase --insert-before` to quickly swap the currenly selected revision with the revision immediately before it. Add `Ctrl` to use `--insert-after` instead.'
BINDINGS+=( --bind "ctrl-alt-x:execute( jjfzf_run jj --no-pager rebase --insert-after {2}+ -r {2} )+$RELOAD+up" )

# Redo
KEY[redo]="Alt-Y"
RUN[redo]="jjfzf_run jj --no-pager redo"
DOC[redo]='Use `jj redo` to redo the last undo operation performed by `jj undo`.'

# Undo
KEY[undo]="Alt-Z"
RUN[undo]="jjfzf_run jj --no-pager undo"
DOC[undo]='Use `jj undo` to undo the last operation performed by `jj` that was not previously undone.'

# Describe
KEY[describe]="Ctrl-D"
RUN[describe]="jjfzf_describe_commit {2}"
DOC[describe]='Use `jj describe` to describe the currently selected revision.'
jjfzf_describe_commit()
(
  REV="${1-@}"
  CONFIG=()
  if test true == $(jj --no-pager --ignore-working-copy log --no-graph \
		       -r "$REV" -T 'self.parents().len() > 1') ; then
    QMSG=$($JJFZF_ABSPATHLIB/draft.sh "$REV" | jjfzf_config_quote)
    CONFIG+=(--config="template-aliases.default_commit_description=$QMSG")
  fi
  export JJFZF_EDITOR="${JJ_EDITOR-}"			# preserve user setting
  export JJ_EDITOR="$JJFZF_ABSPATHLIB/editor.sh"	# wrapper that rejects non-edits
  jjfzf_run +e jj describe --edit "${CONFIG[@]}" "$REV"
)
export -f jjfzf_describe_commit

# Describe with LLM assistance
RUN[synth]="jjfzf_describe_llm {2}"
DOC[synth]='Use `jj describe` to edit a synthetic LLM generated description of the currently selected revision.'
KEY[synth]="Ctrl-S"
jjfzf_describe_llm()
(
  set -Eeuo pipefail
  REV="${1-@}"
  CONFIG=()
  COMMIT=$($JJFZFT 'if(description, "", commit_id)' -r "$REV")
  if test -n "$COMMIT" ; then
    echo '[template-aliases]'			>  $JJFZF_TEMPD/llmdraft.toml
    echo -n "default_commit_description="	>> $JJFZF_TEMPD/llmdraft.toml
    $JJFZF_ABSPATHLIB/gen-message.py --dup-output "$COMMIT" |
      jjfzf_config_quote '' ''			>> $JJFZF_TEMPD/llmdraft.toml # $'\n'
    CONFIG+=( --config-file $JJFZF_TEMPD/llmdraft.toml )
  fi
  export JJFZF_EDITOR="${JJ_EDITOR-}"			# preserve $JJ_EDITOR user settings
  export JJ_EDITOR="$JJFZF_ABSPATHLIB/editor.sh"	# use hash-comparing wrapper
  jjfzf_run +e jj describe --edit "${CONFIG[@]}" "$REV"
)
export -f jjfzf_describe_llm

# Edit
KEY[edit]="Ctrl-E"
RUN[edit]="jjfzf_run jj --no-pager \$($JJFZFT \"if(immutable,'new','edit')\" -r {2}) {2}"
DOC[edit]='Use `jj {edit|new}` to set the currently selected revision (or divergent commit) as the working-copy revision. Will create a new empty commit if the selected revision is immutable.'

# Enter - commit info
case "$ENTER" in
  -c)	BINDINGS+=( --bind 'enter:become( jjfzf_list_commit_ids {2} )' ) ;;
  +c)	BINDINGS+=( --bind 'enter:become( jjfzf_list_commit_ids {+2} )' ) ;;
  -r)	BINDINGS+=( --bind 'enter:become( jjfzf_list_change_ids {2} )' ) ;;
  +r)	BINDINGS+=( --bind 'enter:become( jjfzf_list_change_ids {+2} )' ) ;;
  -s)	BINDINGS+=( --bind 'enter:become( jjfzf_revset )' ) ;;
  *)	BINDINGS+=( --bind 'enter:execute( jjfzf_full_history {2} )' ) ;;
esac

# Log history
KEY[log]="Ctrl-L"
BINDINGS+=( --bind 'ctrl-l:execute( jjfzf_selected_history {+2} )' )
DOC[log]='Use `jj log` to browse the history including patches, for the selected revisions, or the ancestry of a single revision.'
jjfzf_selected_history()
(
  set -Eeuo pipefail
  if test -n "${2-}" ; then
    ALL="$(jjfzf_ccrevs "$@")"
  else
    ALL="..${1-@}"
  fi
  jjfzf_full_history "$ALL"
)
export -f jjfzf_selected_history

# New
KEY[new]="Ctrl-N"	POST[new]="+first"
RUN[new]='jjfzf_run jj --no-pager new $(jjfzf_chronological_change_ids {+2})'
DOC[new]='Use `jj new` to create a new revision on top of the currently selected revision(s).'

# Oplog Commits
KEY[oplog]="Ctrl-O"
RUN[oplog]="jjfzf_run +x +e '$JJFZF_ABSPATHLIB'/oplog.sh"
DOC[oplog]='Use `jj operation log` to browse the recent operations log. Use hotkeys to view operation diffs and history. Undo operations or restore its working copy into a new commit.'

# Push & fetch from remotes
KEY[push]="Ctrl-P"	POST[new]="+first"
DOC[push]='Use `jj git fetch` and `jj git push --tracked --deleted` to update the local and remote repositories. Pushing needs confirmation after a dry-run. Tries to push all refs if no revisions are currently selected.'
RUN[push]="jjfzf_push {2} {+2}"
jjfzf_push()
(
  set -Eeuo pipefail
  REVS=( --tracked --deleted )
  if test ${#@} -gt 2 -o "$1" != "$2" ; then # fzf selection beyond pointer
    shift # eat pointer
    ALL="$(jjfzf_ccrevs "$@")" &&
      REVS=( -r "$ALL" )
  fi
  STATUS=0
  jjfzf_run +n jj git fetch $JJFZF_COLOR $JJFZF_KEEPCOMMITS \
    || STATUS=$?
  if test $STATUS == 0 ; then
    jjfzf_run +n jj git push $JJFZF_COLOR "${REVS[@]}" --dry-run > $JJFZF_TEMPD/push.log 2>&1 \
      || STATUS=$?
    cat $JJFZF_TEMPD/push.log
  fi
  if test $STATUS != 0 || grep -qEi 'nothing *changed|won.?t push|rejected *commit' $JJFZF_TEMPD/push.log ; then
    read -p "Press Enter..."
  else
    read -p 'Proceed with actual push and submit changes? (y/N) ' YN
    [[ "${YN:0:1}" =~ [yY] ]] || exit 0
    jjfzf_run +n jj git push "${REVS[@]}"
  fi
  jjfzf_load_and_status
)
export -f jjfzf_push

# Evolog Commits
KEY[evolog]="Ctrl-V"
DOC[evolog]='Use `jj evolog` to browse the evolution of the selected revision. Inject historic commits into the ancestry without changing descendants.'
RUN[evolog]="jjfzf_run +x +e '$JJFZF_ABSPATHLIB'/evolog.sh {2}"

# Subshell
KEY[shell]="Ctrl-Z"
DOC[shell]='Start interactive subshell.'
BINDINGS+=( --bind "ctrl-z:execute( jjfzf_exec_usershell )+execute( jjfzf_load_and_status )+$RELOAD+refresh-preview" )
# This needs to run execute() twice, because of the exec in jjfzf_exec_usershell

# Reload
KEY[reload]="F5"
DOC[reload]='Reload the revset.'
BINDINGS+=( --bind "f5:execute( jjfzf_load_and_status )+$RELOAD+refresh-preview" )

# Interactive Revset
BINDINGS+=( --bind 'change:reload: jjfzf_revset_log {q} ' )
jjfzf_revset_log()
(
  Q="${1-}"
  if test "${Q:0:1}" != " " &&
      jj --no-pager --ignore-working-copy log --no-graph -T '' -r "@&($Q)" >/dev/null 2>&1 ; then
    echo "$Q" > $JJFZF_REVSET_OVERRIDE
  else
    rm -f $JJFZF_REVSET_OVERRIDE
  fi
  jjfzf_load --stdout
)
export -f jjfzf_revset_log

# Ctrl-F toggle FZF vs Revset
export JJFZF_PROMPT1="Revset > " JJFZF_ILABEL1="$(echo ' Ctrl-F: fzf-filter ⫶ Alt-Enter: save-revset ' | jjfzf_bold_keys)"
export JJFZF_PROMPT2="fzf > "    JJFZF_ILABEL2="$(echo ' Ctrl-F: Revset ' | jjfzf_bold_keys)"
BINDINGS+=( --disabled --prompt "$JJFZF_PROMPT1" )
BINDINGS+=( --bind 'ctrl-f:transform: jjfzf_fzf_transform' )
jjfzf_fzf_transform()
(
  # https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode-using-a-single-key-binding
  if [[ ! $FZF_PROMPT =~ Revset ]] ; then
    T="rebind(change)+rebind(alt-enter)+change-prompt($JJFZF_PROMPT1)+disable-search"
    T="$T+change-input-label($JJFZF_ILABEL1)"
    T="$T+change-ghost()"
    T="$T+transform-query:echo {q} > $JJFZF_TEMPD/q_fzf ; cat $JJFZF_TEMPD/q_revset"
  else
    T="unbind(change)+unbind(alt-enter)+change-prompt($JJFZF_PROMPT2)+enable-search"
    T="$T+change-input-label($JJFZF_ILABEL2)"
    T="$T+transform-query:echo {q} > $JJFZF_TEMPD/q_revset ; cat $JJFZF_TEMPD/q_fzf"
  fi
  echo "$T" # fzf transform instructions
)
export -f jjfzf_fzf_transform
BINDINGS+=( --bind 'ctrl-f,focus:+transform-ghost: [[ ! $FZF_PROMPT =~ Revset ]] && R={2} && echo -n "${R:0:12}" ' )

# Persist Revset
BINDINGS+=( --input-label="$JJFZF_ILABEL1" )
BINDINGS+=( --bind 'alt-enter:execute-silent( jjfzf_set_revset {q} )+reload( jjfzf_load --stdout )+clear-query' )
BINDINGS+=( --info-command='echo -e " \x1b[33;1m$FZF_POS\x1b[m/$FZF_INFO ⫶ all: $(jjfzf_revset)"' )
#KEY[revset]="Alt-Enter" # TODO: for --help only
#DOC[revset]='Persist current revset in repo configuration.'
jjfzf_set_revset()
(
  if test -z "${1-}" ; then			# reset
    if test "$(jj --no-pager --ignore-working-copy config get jj-fzf.log_revset 2>/dev/null)" == "" ; then
      RECENT7=' @:: | ancestors(immutable_heads()..,7) | tags() | bookmarks() | remote_bookmarks() | present(trunk()) '
      # toggle default revset
      jj --no-pager --ignore-working-copy config set --repo jj-fzf.log_revset "$RECENT7"
    else
      jj --no-pager --ignore-working-copy config unset --repo jj-fzf.log_revset
    fi
  elif test -r $JJFZF_REVSET_OVERRIDE ; then	# assign new if validated
    jj --no-pager --ignore-working-copy config set --repo jj-fzf.log_revset "$(cat $JJFZF_REVSET_OVERRIDE)"
  fi
  true
)
export -f jjfzf_set_revset

# == RUN commands ==
if [ -v "RUN[${1-}]" ]; then
  KEY="$1" && CMD="${RUN[$KEY]}" ; shift
  if [[ "$CMD" =~ \{ ]] ; then
    CIDS=( $(jjfzf_list_change_ids "${@-@}") )
    test "${#CIDS[@]}" -lt 1 &&
      die "missing revisions for command: $KEY"
    # Placeholder replacments
    while [[ "$CMD" =~ (.*)\{2\}(.*) ]] ; do
      CMD="${BASH_REMATCH[1]}${CIDS[0]}${BASH_REMATCH[2]}"
    done
    while [[ "$CMD" =~ (.*)\{[+]2\}(.*) ]] ; do
      CMD="${BASH_REMATCH[1]}${CIDS[*]}${BASH_REMATCH[2]}"
    done
    [[ "$CMD" =~ \{ ]] &&
      die "failed to run command: $KEY"
  fi
  export JJFZF_LOAD_LIST=true
  bash -c " $CMD "
  exit
fi

# == Process Bindings ==
declare -a CMDS # Sort commands by key binding string (KEY[$cmd])
while IFS= read -r line; do
  CMDS+=("${line#* }")
done < <(for cmd in "${!KEY[@]}"; do echo "${KEY[$cmd]} $cmd"; done | sort)
for cmd in "${CMDS[@]}"; do
  key="${KEY[$cmd],,}"
  post="$RELOAD${POST[$cmd]-}"
  KEYDOCS+=( "${KEY[$cmd]}: $cmd" )
  test -n "${RUN[$cmd]-}" &&
    BINDINGS+=( --bind "$key:execute( ${RUN[$cmd]} )+$post" )
done

# == jjfzf_showkeys ==
declare -p KEYDOCS > $JJFZF_TEMPD/jjfzf_KEYDOCS
jjfzf_showkeys()
(
  set +u
  HEADER_LINES="${LINES-$FZF_LINES}"
  test -n "$FZF_PREVIEW_LEFT" && test "$FZF_PREVIEW_LEFT" -gt $((FZF_COLUMNS / 10)) &&
    HEADER_COLUMNS="$FZF_PREVIEW_LEFT" || HEADER_COLUMNS="$FZF_COLUMNS"
  if test "$(jjfzf_config get jj-fzf.show-keys)" == false -o "$HEADER_LINES" -lt 20 -o "$HEADER_COLUMNS" -lt 20 ; then
    : # echo "Ctrl-H:help Alt-H:showkeys"
  else
    source $JJFZF_TEMPD/jjfzf_KEYDOCS
    FMT_WIDTH="$((HEADER_COLUMNS - 8))"	# Subtract fzf border
    printf '%s\n' "${KEYDOCS[@]}" |
      awk -v WIDTH="$FMT_WIDTH" -f $JJFZF_ABSPATHLIB/ocolumns.awk |
      jjfzf_bold_keys
  fi
)
export -f jjfzf_showkeys
BINDINGS+=( --bind "start,resize,alt-h,f11:+transform-header: jjfzf_showkeys 2>&1 " )

# == PRINTOUT ==
[[ "$PRINTOUT" == --help-bindings ]] && {
  for cmd in "${CMDS[@]}"; do
    echo
    echo "### _${KEY[$cmd]}_:" "**$cmd**"
    echo "${DOC[$cmd]}"
  done
  exit 0
}

# == fzf ==
V=$($JJFZF_ABSPATHLIB/../version.sh | sed 's/-0-g.*//; s/-[1-9][0-9]*-g.*/+/')
FZF_ARGS+=(
  --marker=' '
  --border-label "-[ JJ-FZF ($V) ]-" --color=border:cyan,label:cyan
  --preview-label " Revision Info "
)
$WITH_PREVIEW &&
  FZF_ARGS+=( --preview "jjfzf_full_commit {2} | sed '1{/^$/d}; 3001q' " )
jjfzf_status
export JJFZF_LOAD_LIST=jjfzf_log0
unset FZF_DEFAULT_OPTS FZF_DEFAULT_COMMAND
jjfzf_load --stdout |
  fzf -m "${FZF_ARGS[@]}" "${BINDINGS[@]}" \
      --read0 '-d¸' --accept-nth=2 --with-nth '{1} {4..}' \
      --header-first
# Notes:
# - Initial listing is read async to quickly popup the fzf log view
# - Commands are executed, then the new log is cached in $JJFZF_TEMPD/jjfzf_list and synchronously read by fzf
#   This allows fzf to track the current cursor position
#     --bind 'start,resize:transform-header(env | fgrep FZF)' \
